OperatingSystem := $(shell uname)
ifeq ($(OperatingSystem), Darwin)
	LibSDL := -framework SDL2
else
	LibSDL := -lSDL2
endif

all:
	g++ -std=c++11 DiceInvaders.cpp Engine.cpp Player.cpp Rocket.cpp Aliens.cpp Bomb.cpp $(LibSDL) -fno-exceptions -o DiceInvaders

clean:
	-rm DiceInvaders

